<a href="https://colab.research.google.com/github/routparam12/Diabetes_project_/blob/main/1st_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr = np.array([1,2,3,5])
arr

array([1, 2, 3, 5])

In [ ]:
np.sort(arr)

array([1, 2, 3, 5])

In [ ]:
arr2 = np.array([[6,3,4,6,2],[3,7,1,2,6]])
arr2

array([[6, 3, 4, 6, 2],
       [3, 7, 1, 2, 6]])

In [ ]:
arr3 = np.array([[6,2,1,4,1],[2,3,2,1,1]])
arr3

array([[6, 2, 1, 4, 1],
       [2, 3, 2, 1, 1]])

In [ ]:
arr2 + arr3

array([[12,  5,  5, 10,  3],
       [ 5, 10,  3,  3,  7]])

In [ ]:
ran = np.arange(15)
ran

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
dict1 = {
    "Name" : ["Rishabh","Parmajeet","Balbir"],
    "Salary" : [999999999,33333333,100],
    "city" : ["Dhanbad","Balasore","jhashuguda"]
}

In [ ]:
df = pd.DataFrame(dict1)
df.head()

Name     Salary        city
0    Rishabh  999999999     Dhanbad
1  Parmajeet   33333333    Balasore
2     Balbir        100  jhashuguda

In [ ]:
df['Name'][0]="Rishabhrkr"
df.head()

<ipython-input-25-ab5b6a3d76b6>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Name'][0]="Rishabhrkr"


Name     Salary        city
0  Rishabhrkr  999999999     Dhanbad
1   Parmajeet   33333333    Balasore
2      Balbir        100  jhashuguda

In [ ]:
df.describe

<bound method NDFrame.describe of          Name     Salary        city
0  Rishabhrkr  999999999     Dhanbad
1   Parmajeet   33333333    Balasore
2      Balbir        100  jhashuguda>

In [ ]:
df.info

<bound method DataFrame.info of          Name     Salary        city
0  Rishabhrkr  999999999     Dhanbad
1   Parmajeet   33333333    Balasore
2      Balbir        100  jhashuguda>

In [ ]:
arr2sort = np.argsort(arr2,axis=1)
arr2sort

array([[4, 1, 2, 0, 3],
       [2, 3, 0, 4, 1]])

In [ ]:
arr2.shape #df.shape

(2, 5)

In [ ]:
#changing value
arr2[0,1]=54

In [ ]:
arr2

array([[ 6, 54,  4,  6,  2],
       [ 3,  7,  1,  2,  6]])

In [ ]:
df = pd.read_csv("data.csv")

In [ ]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.head(18)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0     842302         M        17.99         10.38          122.80     1001.0   
1     842517         M        20.57         17.77          132.90     1326.0   
2   84300903         M        19.69         21.25          130.00     1203.0   
3   84348301         M        11.42         20.38           77.58      386.1   
4   84358402         M        20.29         14.34          135.10     1297.0   
5     843786         M        12.45         15.70           82.57      477.1   
6     844359         M        18.25         19.98          119.60     1040.0   
7   84458202         M        13.71         20.83           90.20      577.9   
8     844981         M        13.00         21.82           87.50      519.8   
9   84501001         M        12.46         24.04           83.97      475.9   
10    845636         M        16.02         23.24          102.70      797.8   
11  84610002         M        15.78         17.89          103.60      781.0   
12    846226         M        19.17         24.80          132.40     1123.0   
13    846381         M        15.85         23.95          103.70      782.7   
14  84667401         M        13.73         22.61           93.60      578.3   
15  84799002         M        14.54         27.54           96.73      658.8   
16    848406         M        14.68         20.13           94.74      684.5   
17  84862001         M        16.13         20.68          108.10      798.8   

    smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.11840           0.27760         0.30010              0.14710   
1           0.08474           0.07864         0.08690              0.07017   
2           0.10960           0.15990         0.19740              0.12790   
3           0.14250           0.28390         0.24140              0.10520   
4           0.10030           0.13280         0.19800              0.10430   
5           0.12780           0.17000         0.15780              0.08089   
6           0.09463           0.10900         0.11270              0.07400   
7           0.11890           0.16450         0.09366              0.05985   
8           0.12730           0.19320         0.18590              0.09353   
9           0.11860           0.23960         0.22730              0.08543   
10          0.08206           0.06669         0.03299              0.03323   
11          0.09710           0.12920         0.09954              0.06606   
12          0.09740           0.24580         0.20650              0.11180   
13          0.08401           0.10020         0.09938              0.05364   
14          0.11310           0.22930         0.21280              0.08025   
15          0.11390           0.15950         0.16390              0.07364   
16          0.09867           0.07200         0.07395              0.05259   
17          0.11700           0.20220         0.17220              0.10280   

    ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0   ...          17.33           184.60      2019.0            0.1622   
1   ...          23.41           158.80      1956.0            0.1238   
2   ...          25.53           152.50      1709.0            0.1444   
3   ...          26.50            98.87       567.7            0.2098   
4   ...          16.67           152.20      1575.0            0.1374   
5   ...          23.75           103.40       741.6            0.1791   
6   ...          27.66           153.20      1606.0            0.1442   
7   ...          28.14           110.60       897.0            0.1654   
8   ...          30.73           106.20       739.3            0.1703   
9   ...          40.68            97.65       711.4            0.1853   
10  ...          33.88           123.80      1150.0            0.1181   
11  ...          27.28           136.50      1299.0            0.1396   
12  ...          29.94           151.70      1332.0      