<a href="https://colab.research.google.com/github/routparam12/Diabetes_project_/blob/main/5july_giet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd

In [9]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [10]:
 np.short(arr)

array([1, 2, 3, 4, 5], dtype=int16)

In [12]:
arr2 = np.array([[6,5,3,8,2],[2,7,0,1,7]])
arr2

array([[6, 5, 3, 8, 2],
       [2, 7, 0, 1, 7]])

In [17]:
arr3 =np.array([[2,3,5,8,1],[2,9,0,7,5]])
arr3

array([[2, 3, 5, 8, 1],
       [2, 9, 0, 7, 5]])

In [18]:
arr2 + arr3

array([[ 8,  8,  8, 16,  3],
       [ 4, 16,  0,  8, 12]])

In [22]:
ran = np.arange(20)
ran

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
dict12 ={
    "Name" : ["param","jeet"],
    "salary" : [2000,2500],
    "city" :["bdk","bls"]
}

In [25]:
df =pd.DataFrame(dict12)
df.head()

Name  salary city
0  param    2000  bdk
1   jeet    2500  bls

In [26]:
df.describe

<bound method NDFrame.describe of     Name  salary city
0  param    2000  bdk
1   jeet    2500  bls>

In [27]:
df.info

<bound method DataFrame.info of     Name  salary city
0  param    2000  bdk
1   jeet    2500  bls>

In [28]:
arr2.shape

(2, 5)